export const sampleTasks = [
  {
    id: "001",
    title: "Work with your provider to schedule a survey date.",
    subtitle: "",
    event: "Survey Assessment",
    url: "",
    completed: false,
    online: false,
    visible: true,
    tab: null,
    buttonLabel: null,
    isAutoCompleted: false,
    status: "Pending",
    tabCategory: "Ground Transport",
  },
  {
    id: "002",
    title: "Prepare rooms for your survey.",
    subtitle:
      "(If it's a virtual survey, include closets, basement, cupboards, garage, outdoor items, etc.)",
    event: "Survey Assessment",
    url: "/hhgservice-survey",
    completed: false,
    online: false,
    visible: true,
    tab: null,
    buttonLabel: null,
    isAutoCompleted: false,
    status: "Pending",
    tabCategory: "Ground Transport",
  },
  {
    id: "003",
    title: "Work with your provider to schedule pack and load dates.",
    subtitle: "",
    event: "Pack and Load",
    url: "",
    completed: false,
    online: false,
    visible: true,
    tab: null,
    buttonLabel: null,
    isAutoCompleted: false,
    status: "Pending",
    tabCategory: "Ground Transport",
  },
  {
    id: "004",
    title: "Set aside essential items to keep with you.",
    subtitle:
      "These items should not be included with the belongings the provider will handle (e.g., legal documents, medicines, keys, valuable items). Unplug Appliances - Unplug appliances 24 to 48 hours before load.",
    event: "Pack and Load",
    url: "",
    completed: false,
    online: false,
    visible: true,
    tab: null,
    buttonLabel: null,
    isAutoCompleted: false,
    status: "Pending",
    tabCategory: "Air Transport",
  },
  {
    id: "005",
    title: "Work with the provider to schedule delivery out of storage date.",
    subtitle: "",
    event: "Storage",
    url: "",
    completed: false,
    online: false,
    visible: true,
    tab: null,
    buttonLabel: null,
    isAutoCompleted: false,
    status: "Pending",
    tabCategory: "Storage",
  },
  {
    id: "006",
    title: "Complete Home Preparations at Destination.",
    subtitle:
      "Complete any tasks, like painting, carpet cleaning, or other necessary preparations, before your items arrive.",
    event: "Delivery",
    url: "",
    completed: false,
    online: false,
    visible: true,
    tab: null,
    buttonLabel: null,
    isAutoCompleted: false,
    status: "Pending",
    tabCategory: "Ground Transport",
  },
  {
    id: "007",
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    subtitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    event: "Delivery",
    url: "",
    completed: false,
    online: false,
    visible: true,
    tab: null,
    buttonLabel: null,
    isAutoCompleted: false,
    status: "Pending",
    tabCategory: "Storage",
  },
  {
    id: "008",
    title: "Clear personal items from your vehicle including the trunk.",
    subtitle: "",
    event: "Vehicle Pick-up",
    url: "",
    completed: false,
    online: false,
    visible: true,
    tab: null,
    buttonLabel: null,
    isAutoCompleted: false,
    status: "Pending",
    tabCategory: "Ground Transport",
  },
  {
    id: "009",
    title: "Take pictures of your vehicle's condition on pickup day.",
    subtitle:
      "Take pictures of your vehicle on the day your driver arrives for pickup to document any pre-existing conditions.",
    event: "Vehicle Pick-up",
    url: "",
    completed: false,
    online: false,
    visible: true,
    tab: null,
    buttonLabel: null,
    isAutoCompleted: false,
    status: "Pending",
    tabCategory: "Ground Transport",
  },
  {
    id: "010",
    title:
      "Work with your provider to schedule pet pickup and delivery dates with provider.",
    subtitle: "",
    event: "Pet Relocation",
    url: "",
    completed: false,
    online: false,
    visible: true,
    tab: null,
    buttonLabel: null,
    isAutoCompleted: false,
    status: "Pending",
    tabCategory: "Air Transport",
  },
  {
    id: "011",
    title: "Check Vaccinations – ensure all vaccinations are up to date.",
    subtitle: "",
    event: "Pet Relocation",
    url: "",
    completed: false,
    online: false,
    visible: true,
    tab: null,
    buttonLabel: null,
    isAutoCompleted: false,
    status: "Pending",
    tabCategory: "Air Transport",
  },
  {
    id: "020",
    title: "Households goods form",
    subtitle: "",
    event: null,
    url: "/dashboard/hhg-intake?stepName=hhg",
    completed: false,
    online: true,
    visible: true,
    tab: null,
    buttonLabel: null,
    isAutoCompleted: false,
    status: "Pending",
    tabCategory: "Ground Transport",
  },
  {
    id: "021",
    title: "Vehicle intake form",
    subtitle: "",
    event: null,
    url: "/dashboard/hhg-intake?stepName=vehicle",
    completed: true,
    online: true,
    visible: true,
    tab: null,
    buttonLabel: null,
    isAutoCompleted: true,
    status: "Completed",
    tabCategory: "Ground Transport",
  },
  {
    id: "022",
    title: "Pet Intake form",
    subtitle: "",
    event: null,
    url: "/dashboard/hhg-intake?stepName=pet",
    completed: false,
    online: true,
    visible: true,
    tab: null,
    buttonLabel: null,
    isAutoCompleted: false,
    status: "Pending",
    tabCategory: "Air Transport",
  },
  {
    id: "023",
    title: "High value inventory form",
    subtitle: "",
    event: null,
    url: "/dashboard/hvi-intake",
    completed: false,
    online: true,
    visible: true,
    tab: null,
    buttonLabel: null,
    isAutoCompleted: false,
    status: "Pending",
    tabCategory: "Storage",
  },
  {
    id: "033",
    title: "Schedule your dates - ground transport",
    subtitle:
      "Work with your provider to schedule your 3-day vehicle pick up window.",
    event: "Pick up and load",
    url: "",
    completed: false,
    online: false,
    visible: true,
    tab: null,
    buttonLabel: null,
    isAutoCompleted: false,
    status: "Pending",
    tabCategory: "Ground Transport",
  },
  {
    id: "034",
    title: "Prepare your vehicle for ground pick up",
    subtitle:
      "Clear your personal items from your vehicle including your trunk.",
    event: "Pick up and load",
    url: "",
    completed: false,
    online: false,
    visible: true,
    tab: null,
    buttonLabel: null,
    isAutoCompleted: false,
    status: "Pending",
    tabCategory: "Ground Transport",
  },
  {
    id: "038",
    title: "Schedule your dates - air transport",
    subtitle:
      "Work with your provider to schedule pet pick up and delivery dates.",
    event: "Pick up and load",
    url: "",
    completed: false,
    online: false,
    visible: true,
    tab: null,
    buttonLabel: null,
    isAutoCompleted: false,
    status: "Pending",
    tabCategory: "Air Transport",
  },
  {
    id: "039",
    title: "Check vaccinations - air transport",
    subtitle: "Ensure all your pet's vaccinations are up to date.",
    event: "Pick up and load",
    url: "",
    completed: false,
    online: false,
    visible: true,
    tab: null,
    buttonLabel: null,
    isAutoCompleted: false,
    status: "Pending",
    tabCategory: "Air Transport",
  },
];

export const hhgTaskList = [
  {
    status: "NotStarted",
    taskName: "Households goods form",
    taskDescription: "Household goods form",
    dataTestId: "020",
  },
  {
    status: "NotStarted",
    taskName: "Vehicle intake form",
    taskDescription: "Vehicle intake form",
    dataTestId: "021",
  },
  {
    status: "NotStarted",
    taskName: "Pet Intake form",
    taskDescription: "Pet Intake form",
    dataTestId: "022",
  },
];
